name = "intercambio-conexion"
main = "worker.js"
compatibility_date = "2026-09-09"

[vars]
ALLOWED_ORIGIN = "https://TU_USUARIO.github.io"

[[d1_databases]]
binding = "DB"
database_name = "intercambio-conexion"
database_id = "COPIA_AQUI_EL_ID_REAL_DE_TU_BASE_D1"

[triggers]
crons = ["*/20 * * * *"]
