import {Files,uid} from './transfer.js';
import {Connection,encode,decode} from './connection.js';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const get=k=>{try{return localStorage.getItem('iw2.'+k)}catch{return null}},put=(k,v)=>{try{localStorage.setItem('iw2.'+k,v)}catch{}};
const identity={id:get('id')||uid().slice(0,12),name:get('name')||(/Android|iPhone|iPad/i.test(navigator.userAgent)?'Mi móvil':'Mi ordenador')};put('id',identity.id);
const conn=new Connection();let files=null,selected=[],camera=null,scanTimer=null,signalTimer=null,roomOwner=null,answerCode='',peerCode='',oldURLs=[],renderTimer,toastTimer,audioCtx;let service=get('service')??window.INTERCAMBIO_CONFIG?.signalUrl??'';
function toast(s){$('toast').textContent=s;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,11000)}
function view(name){document.querySelectorAll('.view').forEach(e=>e.hidden=e.id!=='view-'+name);document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===name))}
function fmt(n){if(n<1024)return n+' B';const i=Math.min(3,Math.floor(Math.log(n)/Math.log(1024)));return (n/1024**i).toFixed(1)+' '+['B','KiB','MiB','GiB'][i]}
function beep(){if(!$('sound').checked||!audioCtx)return;const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.connect(g);g.connect(audioCtx.destination);g.gain.value=.04;o.frequency.value=650;o.start();o.stop(audioCtx.currentTime+.15)}
function render(){
 const ready=files?.ready();$('connection').textContent=ready?'Conectados':conn.pc?.connectionState==='connected'?'Pendiente de aceptación':'Sin conectar';$('connected').hidden=!files?.peer;
 if(files?.peer){$('peerName').textContent=files.peer.name+' · ID '+files.peer.id;$('verification').textContent=peerCode;$('trust').disabled=files.localTrust;$('trust').textContent=files.localTrust?'Aceptado aquí':'Aceptar este dispositivo'}
 $('destination').textContent=ready?'Enviar a '+files.peer.name:'Conecta y acepta un dispositivo primero.';$('send').disabled=!ready;
 const items=files?[...files.items.values()].reverse():[];
 $('transfers').innerHTML=items.map(t=>{const pct=t.size?Math.floor(t.offset/t.size*100):['Guardado','Descargar','Recibido'].includes(t.state)?100:0;
 let actions='';const btn=(a,label,cls='')=>`<button data-action="${a}" data-id="${t.id}" class="${cls}">${label}</button>`;
 if(t.direction==='in'&&t.state==='Pendiente')actions+=btn('accept','Aceptar archivo','primary')+btn('reject','Rechazar');
 if(['Pendiente','Enviando','Recibiendo'].includes(t.state))actions+=btn('cancel','Cancelar','danger');
 if(t.state==='Descargar')actions+=btn('download','Guardar en Descargas','primary')+btn('saved','Ya está guardado');
 const label=t.state==='Descargar'?'Recibido y verificado · falta guardarlo':t.state==='Recibido'?'Recibido por el otro navegador · falta guardar':t.state;
 return `<article class="card transfer"><strong class="filename">${esc(t.name)}</strong><small>${t.direction==='out'?'Envío':'Recepción'} · ${fmt(t.size)}</small><progress max="100" value="${pct}" aria-label="Progreso ${esc(t.name)}"></progress><div class="meta"><span>${esc(label)}</span><span>${pct}%${t.speed&&t.state==='Enviando'?' · '+fmt(t.speed)+'/s · ~'+Math.ceil((t.size-t.offset)/t.speed)+' s':''}</span></div><div class="actions">${actions}</div></article>`}).join('')||'<article class="card empty">Todavía no hay transferencias en esta conexión.</article>';
}
function scheduleRender(){if(renderTimer)return;renderTimer=setTimeout(()=>{renderTimer=null;render()},120)}
conn.addEventListener('channel',async e=>{clearTimeout(signalTimer);files=new Files(e.detail,identity);const engine=files,observed=new Map();files.addEventListener('update',()=>{for(const t of engine.items.values()){if((!observed.has(t.id)&&t.direction==='in'&&t.state==='Pendiente')||(observed.has(t.id)&&observed.get(t.id)!==t.state&&['Descargar','Guardado'].includes(t.state)))beep();observed.set(t.id,t.state)}scheduleRender()});files.addEventListener('error',e=>toast(e.detail));peerCode=await conn.verification();render();beep();toast('Comprueba el código de verificación y acepta en los dos dispositivos.');view('connect');if(roomOwner)signal('DELETE','/rooms/'+roomOwner.room,null,roomOwner.key).catch(()=>{})});
conn.addEventListener('state',e=>{const labels={new:'Preparando conexión',connecting:'Conectando…',connected:'Pendiente de aceptación',disconnected:'Conexión interrumpida',failed:'No se pudo conectar',closed:'Sin conectar'};$('connection').textContent=labels[e.detail]||e.detail;if(['failed','disconnected'].includes(e.detail))toast('Conexión interrumpida. Mantén ambas páginas abiertas y comprueba la wifi.');});
conn.addEventListener('error',e=>toast(e.detail));
function baseURL(){const u=new URL(location.href);u.hash='';u.search='';return u.href}
function output(value,label,room=false){$('outputBox').hidden=false;$('output').value=value;$('outputLabel').textContent=label;const link=room?baseURL()+'#room='+encodeURIComponent(value):baseURL()+'#code='+encodeURIComponent(value);try{const q=qrcode(0,'L');q.addData(link);q.make();$('qr').innerHTML=q.createSvgTag({cellSize:4,margin:16,scalable:true})}catch{$('qr').innerHTML='<p>Código demasiado largo para un QR. Utiliza Copiar código.</p>'}$('expiry').textContent='Invitación válida durante diez minutos. Mantén esta página abierta.'}
function hasPending(){return files&&[...files.items.values()].some(t=>['Pendiente','Enviando','Recibiendo','Descargar'].includes(t.state))}
async function newConnection(){if(hasPending()&&!confirm('Hay archivos pendientes o sin guardar. ¿Descartar esta conexión?'))return false;clearTimeout(signalTimer);stopScan();if(roomOwner)await signal('DELETE','/rooms/'+roomOwner.room,null,roomOwner.key).catch(()=>{});roomOwner=null;if(files){files.c.close();for(const t of files.items.values()){if(t.url)URL.revokeObjectURL(t.url);await files.removeTemp(t)}}files=null;conn.close();$('connected').hidden=true;peerCode='';render();return true}
async function signal(method,path,body,key){
 if(!service)throw new Error('No hay ayuda de conexión configurada. Utiliza el intercambio manual de códigos.');const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);
 try{const r=await fetch(service.replace(/\/$/,'')+path,{method,headers:{...(body?{'Content-Type':'application/json'}:{}),...(key?{Authorization:'Bearer '+key}:{})},body:body?JSON.stringify(body):undefined,signal:controller.signal});const d=await r.json();if(!r.ok)throw new Error(d.error||'Error en la ayuda de conexión.');return d}finally{clearTimeout(timer)}
}
async function watchRoom(room,key,exp){if(roomOwner?.key!==key)return;if(Date.now()>exp){toast('La sala ha caducado. Crea otra invitación.');return}try{const r=await signal('GET','/rooms/'+room+'/answer',null,key);if(roomOwner?.key!==key)return;if(r.answer){const d=await decode(r.answer);await conn.accept(d);return}}catch(e){toast('No se pudo consultar la sala: '+e.message)}if(roomOwner?.key===key)signalTimer=setTimeout(()=>watchRoom(room,key,exp),2500)}
async function create(){if(!await newConnection())return;const v=await conn.create(),code=await encode(v);if(service){try{const r=await signal('POST','/rooms',{offer:code});roomOwner=r;output(r.room,'Escanea el QR o introduce este código de sala en el otro dispositivo.',true);watchRoom(r.room,r.key,v.exp);return}catch(e){toast('La ayuda de conexión no responde. Puedes continuar con el código manual. '+e.message)}}output(code,'Invitación: escanéala en el otro dispositivo. Después trae su respuesta a esta página.');}
async function apply(text){const value=await decode(text);if(value.type==='offer'&&!await newConnection())return;const answer=await conn.accept(value);if(answer){answerCode=await encode(answer);output(answerCode,'Respuesta: escanéala o pégala en el dispositivo que creó la invitación.');$('showAnswer').hidden=false}else{toast('Respuesta aplicada. Estableciendo conexión…');$('expiry').textContent='Respuesta aplicada. Espera a que conecten los navegadores.'}}
async function join(room){room=room.toUpperCase().replace(/[\s-]/g,'');if(!/^[A-Z2-7]{16}$/.test(room))throw new Error('Escribe los 16 caracteres del código de sala.');if(!await newConnection())return;const r=await signal('GET','/rooms/'+room),offer=await decode(r.offer),answer=await conn.accept(offer);const code=await encode(answer);await signal('POST','/rooms/'+room+'/answer',{answer:code});toast('Respuesta enviada. Espera a que se conecten los navegadores.');}
async function scan(){stopScan();if(!navigator.mediaDevices?.getUserMedia)throw new Error('No hay acceso a cámara. Abre el enlace HTTPS de GitHub Pages.');camera=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});$('camera').hidden=false;$('video').srcObject=camera;await $('video').play();const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d',{willReadFrequently:true});const tick=()=>{if(!camera)return;if($('video').videoWidth){canvas.width=Math.min(900,$('video').videoWidth);canvas.height=Math.round(canvas.width*$('video').videoHeight/$('video').videoWidth);ctx.drawImage($('video'),0,0,canvas.width,canvas.height);const data=ctx.getImageData(0,0,canvas.width,canvas.height),qr=jsQR(data.data,canvas.width,canvas.height,{inversionAttempts:'dontInvert'});if(qr){stopScan();consume(qr.data).catch(e=>toast(e.message));return}}scanTimer=setTimeout(tick,200)};tick()}
function stopScan(){clearTimeout(scanTimer);camera?.getTracks().forEach(t=>t.stop());camera=null;$('camera').hidden=true;$('video').srcObject=null}
async function consume(s){if(s.startsWith('http')){const params=new URLSearchParams(new URL(s).hash.slice(1));if(params.has('room'))return join(params.get('room'));}return apply(s)}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.view){view(b.dataset.view);return}if(!b.dataset.action)return;b.disabled=true;try{const t=files.items.get(b.dataset.id);switch(b.dataset.action){case'accept':await files.accept(t.id);beep();break;case'reject':await files.cancel(t.id,true);break;case'cancel':await files.cancel(t.id);break;case'download':{const a=document.createElement('a');a.href=t.url;a.download=t.name;document.body.append(a);a.click();a.remove();toast('Comprueba la descarga. Después pulsa Ya está guardado para liberar el temporal.');break}case'saved':if(confirm('¿Has comprobado que el archivo está guardado? Se liberará la copia temporal.'))await files.saved(t.id);break}render()}catch(e){toast(e.message)}finally{b.disabled=false}});
function action(id,fn){$(id).addEventListener('click',async()=>{const b=$(id);b.disabled=true;try{await fn()}catch(e){toast(e.message)}finally{b.disabled=false}})}
action('create',create);action('apply',()=>consume($('input').value.trim()));action('copy',async()=>{await navigator.clipboard.writeText($('output').value);toast('Código copiado.')});action('scan',scan);action('stopScan',stopScan);action('joinRoom',()=>join($('room').value));action('showAnswer',()=>output(answerCode,'Respuesta de esta conexión.'));
action('trust',()=>{files.trust();render()});action('disconnect',newConnection);
action('send',()=>{if(!selected.length)throw new Error('Selecciona archivos primero.');files.enqueue(selected);selected=[];$('files').value='';selection();view('activity');render()});
function selection(){ $('selection').textContent=selected.length?selected.length+' archivo(s) · '+fmt(selected.reduce((s,f)=>s+f.size,0)):'Ningún archivo seleccionado.'}
$('files').addEventListener('change',()=>{selected=[...$('files').files];selection()});$('drop').addEventListener('dragover',e=>{e.preventDefault();$('drop').classList.add('drag')});$('drop').addEventListener('dragleave',()=>$('drop').classList.remove('drag'));$('drop').addEventListener('drop',e=>{e.preventDefault();$('drop').classList.remove('drag');selected=[...e.dataTransfer.files];selection()});window.addEventListener('dragover',e=>e.preventDefault());window.addEventListener('drop',e=>e.preventDefault());
$('name').value=identity.name;function renderIdentity(){$('identity').textContent=identity.name+' · ID '+identity.id}renderIdentity();$('nameForm').addEventListener('submit',e=>{e.preventDefault();identity.name=$('name').value.trim()||'Mi dispositivo';put('name',identity.name);renderIdentity();toast('Nombre guardado. Se mostrará al conectar de nuevo.')});
$('theme').value=get('theme')||'dark';function theme(){document.body.classList.toggle('light',$('theme').value==='light');put('theme',$('theme').value)}$('theme').addEventListener('change',theme);theme();$('sound').checked=get('sound')==='true';$('sound').addEventListener('change',()=>put('sound',$('sound').checked));
$('service').value=service;$('roomBox').hidden=!service;action('saveService',()=>{const s=$('service').value.trim();if(s){const u=new URL(s);if(u.protocol!=='https:'||u.username||u.password||u.search||u.hash)throw new Error('Introduce una URL HTTPS sin credenciales ni parámetros.')}service=s.replace(/\/$/,'');put('service',service);$('roomBox').hidden=!service;toast('Configuración guardada. Se aplicará a la próxima conexión.')});
document.addEventListener('pointerdown',()=>{if(window.AudioContext){audioCtx=new AudioContext();audioCtx.resume().catch(()=>{})}},{once:true});
window.addEventListener('beforeunload',e=>{stopScan();if(hasPending()){e.preventDefault();e.returnValue=''}});
const params=new URLSearchParams(location.hash.slice(1));history.replaceState(null,'',location.pathname+location.search);
if(!window.isSecureContext||!window.RTCPeerConnection||!window.crypto?.subtle){$('unsupported').hidden=false;$('unsupported').textContent='Abre esta app desde el enlace HTTPS de GitHub Pages en un navegador actualizado. No abras index.html directamente.';$('create').disabled=true;$('apply').disabled=true}else{if(params.has('code')){$('input').value=params.get('code');toast('Invitación cargada. Pulsa Usar código para conectar.')}if(params.has('room')){$('room').value=params.get('room');$('roomBox').hidden=false;toast(service?'Sala cargada. Pulsa Entrar en la sala.':'Esta sala necesita la ayuda de conexión configurada en Ajustes.')}}render();
