import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';import{DatabaseSync}from'node:sqlite';
import {Files,uid} from '../transfer.js';import{encode,decode}from'../connection.js';import worker from '../conexion-opcional/worker.js';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));async function until(fn){const start=Date.now();while(!fn()){if(Date.now()-start>6000)throw new Error('UI flow timed out');await sleep(10)}}
class Channel{constructor(){this.readyState='open'}send(data){setImmediate(()=>{if(this.other.readyState==='open')this.other.onmessage?.({data})})}close(){if(this.readyState==='closed')return;this.readyState='closed';this.onclose?.();this.other.close()}}
const connections=new Map();
class FakeConnection extends EventTarget{
 constructor(){super();this.pc={connectionState:'new'}}
 async create(){this.session=uid();connections.set(this.session,this);return{type:'offer',session:this.session,sdp:'v=0\r\na=fingerprint:sha-256 AA:BB\r\n',exp:Date.now()+600000}}
 async accept(value){if(value.type==='offer'){this.first=connections.get(value.session);this.first.second=this;return{...value,type:'answer'}}const a=new Channel(),b=new Channel();a.other=b;b.other=a;this.channel=a;this.second.channel=b;this.pc.connectionState=this.second.pc.connectionState='connected';this.dispatchEvent(new CustomEvent('channel',{detail:a}));this.second.dispatchEvent(new CustomEvent('channel',{detail:b}));return null}
 close(){this.channel?.close();this.pc=null}
}
function dom(){const nodes=new Map();for(const m of readFileSync(new URL('../index.html',import.meta.url),'utf8').matchAll(/id="([^"]+)"/g)){nodes.set(m[1],{value:'',hidden:false,disabled:false,dataset:{},textContent:'',innerHTML:'',addEventListener(type,fn){this[type]=fn},classList:{toggle(){},add(){},remove(){}}})}nodes.get('theme').value='dark';return{nodes,getElementById:id=>{if(!nodes.has(id))throw new Error('Missing ID '+id);return nodes.get(id)},querySelectorAll:()=>[],addEventListener(){},body:{classList:{toggle(){}}}}}
test('both PIN forms connect automatically without a second consent step',async()=>{
 const db=new DatabaseSync(':memory:');db.exec(readFileSync(new URL('../conexion-opcional/schema.sql',import.meta.url),'utf8'));const env={ALLOWED_ORIGIN:'https://example.github.io',DB:{prepare(sql){return{bind(...args){return{first:async()=>db.prepare(sql).get(...args)||null,run:async()=>({meta:{changes:db.prepare(sql).run(...args).changes}})}}}},batch:async a=>Promise.all(a.map(x=>x.run()))}};
 const timers=new Set();function timer(fn,ms){const h=setTimeout(fn,Math.min(ms,ms===2500?30:ms));timers.add(h);return h}
 const make=()=>{const document=dom(),store=new Map(),ctx={Files,uid,Connection:FakeConnection,encode,decode,document,localStorage:{getItem:k=>store.get(k)??null,setItem:(k,v)=>store.set(k,v)},window:{isSecureContext:true,RTCPeerConnection:true,crypto,INTERCAMBIO_CONFIG:{signalUrl:'https://signal.workers.dev'},addEventListener(){}},navigator:{userAgent:'Test',onLine:true},location:{pathname:'/app/',search:''},history:{replaceState(){}},setTimeout:timer,clearTimeout,setInterval,clearInterval,confirm:()=>true,URL,AbortController,console,fetch:async(url,init)=>worker.fetch(new Request(url,{...init,headers:{...init.headers,Origin:env.ALLOWED_ORIGIN,'CF-Connecting-IP':'192.0.2.1'}}),env)};vm.runInNewContext(readFileSync(new URL('../app.js',import.meta.url),'utf8').replace(/^import .*;\n/gm,''),ctx);return document};
 const A=make(),B=make();A.nodes.get('pin').value=B.nodes.get('pin').value='004321';A.nodes.get('deviceName').value='Ordenador';B.nodes.get('deviceName').value='Móvil';
 try{await Promise.all([A.nodes.get('connectForm').submit({preventDefault(){}}),B.nodes.get('connectForm').submit({preventDefault(){}})]);await until(()=>A.nodes.get('connection').textContent==='Conectados'&&B.nodes.get('connection').textContent==='Conectados');assert.equal(A.nodes.get('peerName').textContent,'Conectado con Móvil');assert.equal(B.nodes.get('peerName').textContent,'Conectado con Ordenador');assert.equal(A.nodes.get('send').disabled,false);assert.equal(B.nodes.get('send').disabled,false);assert.ok(!A.nodes.has('trust'));assert.ok(!A.nodes.has('qr'));}
 finally{await A.nodes.get('disconnect').click();await B.nodes.get('disconnect').click();for(const h of timers)clearTimeout(h);db.close();connections.clear()}
});
