import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import worker from '../conexion-opcional/worker.js';
const origin='https://domingoprueba.github.io',first='a'.repeat(64),second='b'.repeat(64),third='c'.repeat(64);
function environment(){const db=new DatabaseSync(':memory:');db.exec(readFileSync(new URL('../conexion-opcional/schema.sql',import.meta.url),'utf8'));return{db,env:{ALLOWED_ORIGIN:origin,DB:{prepare(sql){return{bind(...args){return{first:async()=>db.prepare(sql).get(...args)||null,run:async()=>({meta:{changes:db.prepare(sql).run(...args).changes}})}}}},async batch(stmts){return Promise.all(stmts.map(s=>s.run()))}}}}}
async function req(env,method,path,body,key,customOrigin=origin,ip='192.0.2.4'){return worker.fetch(new Request('https://example.workers.dev'+path,{method,headers:{Origin:customOrigin,'CF-Connecting-IP':ip,...(body?{'Content-Type':'application/json'}:{}),...(key?{Authorization:'Bearer '+key}:{})},body:body?JSON.stringify(body):undefined}),env)}
const join=(env,pin,client,ip)=>req(env,'POST','/pin/join',{pin,client,offer:'IW2.J.abc'},null,origin,ip);
async function joined(env,pin,client,ip){const r=await join(env,pin,client,ip);assert.equal(r.status,200,await r.clone().text());return r.json()}
test('same six-digit PIN pairs two peers, including leading zeros; PIN is not stored in plaintext',async()=>{const{db,env}=environment();const a=await joined(env,'001234',first),b=await joined(env,'001234',second);assert.equal(a.role,'first');assert.equal(b.role,'second');assert.equal(a.id,b.id);assert.equal(b.offer,'IW2.J.abc');assert.ok(a.expires-Date.now()<=180000);assert.equal((await joined(env,'001234',first)).id,a.id);assert.equal((await joined(env,'001234',second)).id,a.id);assert.equal((await join(env,'001234',third)).status,409);const rows=db.prepare('SELECT * FROM pin_sessions').all();assert.equal(rows.length,1);assert.ok(!JSON.stringify(rows).includes('001234'));db.close()});
test('simultaneous joins elect exactly one first peer and one second peer',async()=>{const{db,env}=environment();const[a,b]=await Promise.all([joined(env,'928375',first),joined(env,'928375',second)]);assert.equal(a.id,b.id);assert.deepEqual([a.role,b.role].sort(),['first','second']);db.close()});
test('different PINs do not connect; no false same-WiFi claim or IP-based rejection',async()=>{const{db,env}=environment();const a=await joined(env,'123456',first),b=await joined(env,'654321',second);assert.notEqual(a.id,b.id);assert.equal(b.role,'first');const c=await joined(env,'123456',third,'2001:db8::abcd');assert.equal(c.id,a.id);assert.equal(c.role,'second');db.close()});
test('protected polling, responder-only answer, idempotence, consumed PIN and cancellation',async()=>{const{db,env}=environment();const a=await joined(env,'111222',first);await joined(env,'111222',second);const path='/pin/'+a.id;assert.equal((await req(env,'GET',path)).status,403);assert.equal((await req(env,'GET',path,null,third)).status,403);assert.equal((await req(env,'POST',path+'/answer',{answer:'IW2.J.xyz'},first)).status,403);assert.equal((await req(env,'POST',path+'/answer',{answer:'IW2.J.xyz'},second)).status,200);assert.equal((await req(env,'POST',path+'/answer',{answer:'IW2.J.xyz'},second)).status,200);assert.equal((await req(env,'POST',path+'/answer',{answer:'IW2.J.other'},second)).status,409);assert.equal((await(await req(env,'GET',path,null,first)).json()).answer,'IW2.J.xyz');assert.equal((await(await req(env,'GET',path,null,second)).json()).answer,null);assert.equal((await req(env,'POST',path+'/connected',{},first)).status,200);assert.equal((await join(env,'111222',third)).status,409);assert.equal(db.prepare('SELECT offer FROM pin_sessions').get().offer,null);assert.equal((await req(env,'DELETE',path,null,second)).status,200);assert.equal((await req(env,'GET',path,null,first)).status,410);db.close()});
test('expiry allows new PIN session and rejects stale credentials',async()=>{const{db,env}=environment();const a=await joined(env,'123789',first);db.prepare('UPDATE pin_sessions SET expires=0').run();assert.equal((await req(env,'GET','/pin/'+a.id,null,first)).status,410);const b=await joined(env,'123789',second);assert.notEqual(a.id,b.id);assert.equal(b.role,'first');assert.equal((await req(env,'GET','/pin/'+b.id,null,first)).status,403);db.close()});
test('invalid PINs, old endpoints, origin check, missing binding, and attempt rate limit',async()=>{const{db,env}=environment();assert.equal((await req({},'POST','/pin/join',{})).status,503);assert.equal((await req(env,'POST','/pin/join',{},null,'https://evil.example')).status,403);for(const pin of ['12345','1234567','abcdef',123456])assert.equal((await join(env,pin,first)).status,400);for(let i=0;i<8;i++)assert.equal((await join(env,String(200000+i),first)).status,200);assert.equal((await join(env,'987654',second)).status,429);assert.equal((await req(env,'GET','/rooms/AAAAAAAAAAAAAAAA')).status,404);db.close()});
