import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import worker from '../conexion-opcional/worker.js';
const origin='https://domingoprueba.github.io';
function environment(){const db=new DatabaseSync(':memory:');db.exec(readFileSync(new URL('../conexion-opcional/schema.sql',import.meta.url),'utf8'));return{db,env:{ALLOWED_ORIGIN:origin,DB:{prepare(sql){return{bind(...args){return{first:async()=>db.prepare(sql).get(...args)||null,run:async()=>({meta:{changes:db.prepare(sql).run(...args).changes}})}}}},async batch(stmts){return Promise.all(stmts.map(s=>s.run()))}}}}}
async function req(env,method,path,body,key,customOrigin=origin){return worker.fetch(new Request('https://example.workers.dev'+path,{method,headers:{Origin:customOrigin,'CF-Connecting-IP':'192.0.2.4',...(body?{'Content-Type':'application/json'}:{}),...(key?{Authorization:'Bearer '+key}:{})},body:body?JSON.stringify(body):undefined}),env)}
test('room create, read, owner auth, single answer, delete, origin and expiry',async()=>{const{db,env}=environment();let r=await req(env,'POST','/rooms',{offer:'IW2.J.abc'});assert.equal(r.status,200);const room=await r.json();assert.match(room.room,/^[A-Z2-7]{16}$/);assert.equal((await req(env,'GET','/rooms/'+room.room+'/answer')).status,403);assert.equal((await req(env,'GET','/rooms/'+room.room)).status,200);assert.equal((await req(env,'POST','/rooms/'+room.room+'/answer',{answer:'IW2.J.xyz'})).status,200);assert.equal((await req(env,'POST','/rooms/'+room.room+'/answer',{answer:'IW2.J.xyz'})).status,409);r=await req(env,'GET','/rooms/'+room.room+'/answer',null,room.key);assert.equal((await r.json()).answer,'IW2.J.xyz');assert.equal((await req(env,'GET','/rooms/'+room.room,null,null,'https://evil.example')).status,403);assert.equal((await req(env,'DELETE','/rooms/'+room.room,null,room.key)).status,200);assert.equal((await req(env,'GET','/rooms/'+room.room)).status,404);const another=await(await req(env,'POST','/rooms',{offer:'IW2.J.abc'})).json();db.prepare('UPDATE rooms SET expires=0 WHERE id=?').run(another.room);assert.equal((await req(env,'GET','/rooms/'+another.room)).status,404);db.close()});
test('bad inputs, missing binding, and per-IP room creation limit',async()=>{const{db,env}=environment();assert.equal((await req({},'GET','/rooms')).status,503);assert.equal((await req(env,'POST','/rooms',{offer:'file payload'})).status,400);for(let i=0;i<10;i++)assert.equal((await req(env,'POST','/rooms',{offer:'IW2.J.abc'})).status,200);assert.equal((await req(env,'POST','/rooms',{offer:'IW2.J.abc'})).status,429);db.close()});
